// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_BaifoJKcabMk445Kwwyq4fnH4hIx_PY',
    appId: '1:141444148607:web:7f5f1bc7a0a87bbfdebe4a',
    messagingSenderId: '141444148607',
    projectId: 'fir-firestore-6a958',
    authDomain: 'fir-firestore-6a958.firebaseapp.com',
    storageBucket: 'fir-firestore-6a958.appspot.com',
    measurementId: 'G-RLL961M7PM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvSvYkP45kymV1A3i0qPToQLypiRTGyFg',
    appId: '1:141444148607:android:7184bb7b7082a543debe4a',
    messagingSenderId: '141444148607',
    projectId: 'fir-firestore-6a958',
    storageBucket: 'fir-firestore-6a958.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYMbgIcWMHXmtIde9jj4DcnzlKKmLDRD0',
    appId: '1:141444148607:ios:cc28371cbee761e6debe4a',
    messagingSenderId: '141444148607',
    projectId: 'fir-firestore-6a958',
    storageBucket: 'fir-firestore-6a958.appspot.com',
    iosBundleId: 'com.example.firebaseSirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYMbgIcWMHXmtIde9jj4DcnzlKKmLDRD0',
    appId: '1:141444148607:ios:ec41544060397c9bdebe4a',
    messagingSenderId: '141444148607',
    projectId: 'fir-firestore-6a958',
    storageBucket: 'fir-firestore-6a958.appspot.com',
    iosBundleId: 'com.example.firebaseSirestore.RunnerTests',
  );
}
